# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload to Play Store internal track"
  lane :internal do
    # Increment version code
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    # Build the release APK
    gradle(
      task: "clean assembleRelease"
    )

    # Build the app bundle
    gradle(
      task: "bundleRelease"
    )

    # Upload to Play Store
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft"
    )
  end

  desc "Build and upload to Play Store beta track"
  lane :beta do
    # Increment version code
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    # Build the release APK
    gradle(
      task: "clean assembleRelease"
    )

    # Build the app bundle
    gradle(
      task: "bundleRelease"
    )

    # Upload to Play Store
    upload_to_play_store(
      track: "beta",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft"
    )
  end

  desc "Build and upload to Play Store production track"
  lane :production do
    # Increment version code
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    # Build the release APK
    gradle(
      task: "clean assembleRelease"
    )

    # Build the app bundle
    gradle(
      task: "bundleRelease"
    )

    # Upload to Play Store
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      release_status: "draft"
    )
  end

  desc "Increment version code"
  private_lane :increment_version_code do |options|
    path = options[:gradle_file_path]
    re = /versionCode (\d+)/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
end
